# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0636c0b6ba27aba1504f4b931fc02bf7ce674e54852fb17e53380237048601358b165368a79c802008a66c190c58262c0a947ea444b036bffd3bf5a65cf87fa

test:
  secret_key_base: 4ba8099ed72ef8beef10960d34e828a13b2cc23568092a31751fb19c221bd737c609569649c69929305f35d2940cf9e24e65df03c561c7b6d3c510c43c4b0e8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
